### ISSUE TITLE
td-agent should sign repo metadata for yum/dnf repos so install can occur on RHEL 8 with repo_checkgpg=1

### ISSUE THREAD

**Issue by justchris1** [fluent-plugins-nursery/fluent-package-builder#313]
NOTE: Was originally posted to https://github.com/fluent/fluentd/issues/3436, but @cosmo0920 asked for this issue to be opened here instead.  It isn't super obvious this is the right place for this, so just let me know if I have the right place if I don't.

td-agent won't operate as a repo on Redhat / Centos 8 (maybe 7 as well?) machines if repo_gpgcheck=1 is specified in the /etc/yum.repos.d configuration file. This prevents the repo metadata from be cryptographically validated to increase the confidence that the proper updates are being applied/installed.

**Describe the bug**
TD should sign its metadata in the yum/dnf repository that it distributes so that it can be validated.

**To Reproduce**
Follow instructions to install the repo in yum.repos.d as described here: https://docs.fluentd.org/installation/install-by-rpm NOTE:  I had to remove the backslashes '\' from the baseurl to get it to work in RHEL 8.  Then open the file installed (/etc/yum.repos.d/td.repo) and insert at the end  `repo_gpgcheck=1`.  Then execute 'dnf install td-agent'.  The following occurs:
```
TreasureData                                                                                                                                                                 3.7 kB/s | 569  B     00:00    
TreasureData                                                                                                                                                                  85 kB/s | 3.1 kB     00:00    
TreasureData                                                                                                                                                                  11 kB/s | 569  B     00:00    
Errors during downloading metadata for repository 'treasuredata':
  - Status code: 404 for http://packages.treasuredata.com/4/redhat/8/x86_64/repodata/repomd.xml.asc (IP: 99.86.230.8)
Error: Failed to download metadata for repo 'treasuredata': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for http://packages.treasuredata.com/4/redhat/8/x86_64/repodata/repomd.xml.asc (IP: 99.86.230.8)
```

**Expected behavior**
The package would install since the repo metadata could be cryptographically verified.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`: Uninstalled at this time
- Operating system: `cat /etc/os-release`: Redhat 8
- Kernel version: `uname -r`: 4.18.0-305.3.1.el8.x86_64

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
Not yet installed.

**Your Error Log**

```
Errors during downloading metadata for repository 'treasuredata':
  - Status code: 404 for http://packages.treasuredata.com/4/redhat/8/x86_64/repodata/repomd.xml.asc (IP: 99.86.230.8)
Error: Failed to download metadata for repo 'treasuredata': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for http://packages.treasuredata.com/4/redhat/8/x86_64/repodata/repomd.xml.asc (IP: 99.86.230.8)
```

**Additional context**

Some high compliance environments are not permitted to use repositories unless repo_gpgcheck=1 due to the potential avenues for targeted attacks on systems. Signing repository metadata enables users to be assured that the published data is valid and made available by the signer.

**Comment by kenhys** [comment]
Yes, currently rpm packages are signed but not for the repository.
For supporting `repo_gpgcheck=1`, it should be signed by  `gpg --detach-sign --armor repodata/repomd.xml `.

ref. https://blog.packagecloud.io/eng/2015/07/20/yum-repository-internals/

**Comment by justchris1** [comment]
> Yes, currently rpm packages are signed but not for the repository.
> For supporting `repo_gpgcheck=1`, it should be signed by `gpg --detach-sign --armor repodata/repomd.xml `.
> 
> ref. https://blog.packagecloud.io/eng/2015/07/20/yum-repository-internals/

Thanks for confirming that.  Is this something that can be fixed?

**Comment by kenhys** [comment]
@justchris1 
I've asked the maintainer of the repository, I got positive feedback, but it seems that it takes some time to deploy.

**Comment by kenhys** [comment]
@justchris1 

FYI: install script is not updated yet, it seems repo_checkgpg=1 will work now.
https://docs.fluentd.org/installation/install-by-rpm#red-hat-centos

**Comment by kenhys** [comment]
TODO: update https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh

**Comment by justchris1** [comment]
@kenhys I manually updated the repo definition in /etc/yum.d and `repo_gpgcheck=1` works now.  Thanks for the help.

Do you have any ability to help get the same issue resolved for fluent-bit? [https://github.com/fluent/fluent-bit/issues/3618](https://github.com/fluent/fluent-bit/issues/3618)  Also, it would be far better to use this signing key (Treasure Data, Inc (Treasure Agent Official Signing key) <support@treasure-data.com>) instead of the personal signing key of Eduardo Silva (https://github.com/fluent/fluent-bit-packaging/issues/23)  I just wanted to raise that to your attention as I think they are important issues related to what you are looking into here.

**Comment by kenhys** [comment]
I don't know how fluent-bit is maintained in their repository, so I'm not sure whether the same sign key should be used. 
Anyway personal signing key is not suitable, I agree.

**Comment by kenhys** [comment]
I've asked the maintainer to update the install script. It will be updated sooner or later.

**Comment by kenhys** [comment]
I've commented https://github.com/fluent/fluent-bit/issues/3618, https://github.com/fluent/fluent-bit-packaging/issues/23. I hope they could take action.
